<?php
// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/Compostage.php");
	include("$currDir/Compostage_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('Compostage');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "Compostage";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`Compostage`.`id`" => "id",
		"if(`Compostage`.`date`,date_format(`Compostage`.`date`,'%d/%m/%Y'),'')" => "date",
		"IF(    CHAR_LENGTH(`Sites1`.`nom`), CONCAT_WS('',   `Sites1`.`nom`), '') /* Lieu compostage */" => "lieu_compostage",
		"IF(    CHAR_LENGTH(`matieres1`.`nom`), CONCAT_WS('',   `matieres1`.`nom`), '') /* Mati&#232;re */" => "matiere",
		"`Compostage`.`poids`" => "poids"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`Compostage`.`id`',
		2 => '`Compostage`.`date`',
		3 => '`Sites1`.`nom`',
		4 => '`matieres1`.`nom`',
		5 => '`Compostage`.`poids`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`Compostage`.`id`" => "id",
		"if(`Compostage`.`date`,date_format(`Compostage`.`date`,'%d/%m/%Y'),'')" => "date",
		"IF(    CHAR_LENGTH(`Sites1`.`nom`), CONCAT_WS('',   `Sites1`.`nom`), '') /* Lieu compostage */" => "lieu_compostage",
		"IF(    CHAR_LENGTH(`matieres1`.`nom`), CONCAT_WS('',   `matieres1`.`nom`), '') /* Mati&#232;re */" => "matiere",
		"`Compostage`.`poids`" => "poids"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`Compostage`.`id`" => "ID",
		"`Compostage`.`date`" => "Date",
		"IF(    CHAR_LENGTH(`Sites1`.`nom`), CONCAT_WS('',   `Sites1`.`nom`), '') /* Lieu compostage */" => "Lieu compostage",
		"IF(    CHAR_LENGTH(`matieres1`.`nom`), CONCAT_WS('',   `matieres1`.`nom`), '') /* Mati&#232;re */" => "Mati&#232;re",
		"`Compostage`.`poids`" => "Poids"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`Compostage`.`id`" => "id",
		"if(`Compostage`.`date`,date_format(`Compostage`.`date`,'%d/%m/%Y'),'')" => "date",
		"IF(    CHAR_LENGTH(`Sites1`.`nom`), CONCAT_WS('',   `Sites1`.`nom`), '') /* Lieu compostage */" => "lieu_compostage",
		"IF(    CHAR_LENGTH(`matieres1`.`nom`), CONCAT_WS('',   `matieres1`.`nom`), '') /* Mati&#232;re */" => "matiere",
		"`Compostage`.`poids`" => "poids"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'lieu_compostage' => 'Lieu compostage', 'matiere' => 'Mati&#232;re');

	$x->QueryFrom = "`Compostage` LEFT JOIN `Sites` as Sites1 ON `Sites1`.`id`=`Compostage`.`lieu_compostage` LEFT JOIN `matieres` as matieres1 ON `matieres1`.`id`=`Compostage`.`matiere` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "Compostage_view.php";
	$x->RedirectAfterInsert = "Compostage_view.php?SelectedID=#ID#";
	$x->TableTitle = "Compostage";
	$x->TableIcon = "resources/table_icons/recycle.png";
	$x->PrimaryKey = "`Compostage`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150);
	$x->ColCaption = array("Date", "Lieu compostage", "Mati&#232;re", "Poids");
	$x->ColFieldName = array('date', 'lieu_compostage', 'matiere', 'poids');
	$x->ColNumber  = array(2, 3, 4, 5);

	// template paths below are based on the app main directory
	$x->Template = 'templates/Compostage_templateTV.html';
	$x->SelectedTemplate = 'templates/Compostage_templateTVS.html';
	$x->TemplateDV = 'templates/Compostage_templateDV.html';
	$x->TemplateDVP = 'templates/Compostage_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Compostage`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Compostage' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Compostage`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Compostage' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`Compostage`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: Compostage_init
	$render=TRUE;
	if(function_exists('Compostage_init')){
		$args=array();
		$render=Compostage_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Compostage_header
	$headerCode='';
	if(function_exists('Compostage_header')){
		$args=array();
		$headerCode=Compostage_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: Compostage_footer
	$footerCode='';
	if(function_exists('Compostage_footer')){
		$args=array();
		$footerCode=Compostage_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>