<?php

// Data functions (insert, update, delete, form) for table Compostage

// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

function Compostage_insert(){
	global $Translation;

	// mm: can member insert record?
	$arrPerm=getTablePermissions('Compostage');
	if(!$arrPerm[1]){
		return false;
	}

	$data['date'] = intval($_REQUEST['dateYear']) . '-' . intval($_REQUEST['dateMonth']) . '-' . intval($_REQUEST['dateDay']);
	$data['date'] = parseMySQLDate($data['date'], '1');
	$data['lieu_compostage'] = makeSafe($_REQUEST['lieu_compostage']);
		if($data['lieu_compostage'] == empty_lookup_value){ $data['lieu_compostage'] = ''; }
	$data['matiere'] = makeSafe($_REQUEST['matiere']);
		if($data['matiere'] == empty_lookup_value){ $data['matiere'] = ''; }
	$data['poids'] = makeSafe($_REQUEST['poids']);
		if($data['poids'] == empty_lookup_value){ $data['poids'] = ''; }
	if($data['lieu_compostage']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Lieu compostage': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['matiere']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Mati&#232;re': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	if($data['poids']== ''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">" . $Translation['error:'] . " 'Poids': " . $Translation['field not null'] . '<br><br>';
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}

	// hook: Compostage_before_insert
	if(function_exists('Compostage_before_insert')){
		$args=array();
		if(!Compostage_before_insert($data, getMemberInfo(), $args)){ return false; }
	}

	$o = array('silentErrors' => true);
	sql('insert into `Compostage` set       `date`=' . (($data['date'] !== '' && $data['date'] !== NULL) ? "'{$data['date']}'" : 'NULL') . ', `lieu_compostage`=' . (($data['lieu_compostage'] !== '' && $data['lieu_compostage'] !== NULL) ? "'{$data['lieu_compostage']}'" : 'NULL') . ', `matiere`=' . (($data['matiere'] !== '' && $data['matiere'] !== NULL) ? "'{$data['matiere']}'" : 'NULL') . ', `poids`=' . (($data['poids'] !== '' && $data['poids'] !== NULL) ? "'{$data['poids']}'" : 'NULL'), $o);
	if($o['error']!=''){
		echo $o['error'];
		echo "<a href=\"Compostage_view.php?addNew_x=1\">{$Translation['< back']}</a>";
		exit;
	}

	$recID = db_insert_id(db_link());

	// hook: Compostage_after_insert
	if(function_exists('Compostage_after_insert')){
		$res = sql("select * from `Compostage` where `id`='" . makeSafe($recID, false) . "' limit 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=array();
		if(!Compostage_after_insert($data, getMemberInfo(), $args)){ return $recID; }
	}

	// mm: save ownership data
	set_record_owner('Compostage', $recID, getLoggedMemberID());

	return $recID;
}

function Compostage_delete($selected_id, $AllowDeleteOfParents=false, $skipChecks=false){
	// insure referential integrity ...
	global $Translation;
	$selected_id=makeSafe($selected_id);

	// mm: can member delete record?
	$arrPerm=getTablePermissions('Compostage');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Compostage' and pkValue='$selected_id'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Compostage' and pkValue='$selected_id'");
	if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
		// delete allowed, so continue ...
	}else{
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: Compostage_before_delete
	if(function_exists('Compostage_before_delete')){
		$args=array();
		if(!Compostage_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'];
	}

	sql("delete from `Compostage` where `id`='$selected_id'", $eo);

	// hook: Compostage_after_delete
	if(function_exists('Compostage_after_delete')){
		$args=array();
		Compostage_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("delete from membership_userrecords where tableName='Compostage' and pkValue='$selected_id'", $eo);
}

function Compostage_update($selected_id){
	global $Translation;

	// mm: can member edit record?
	$arrPerm=getTablePermissions('Compostage');
	$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Compostage' and pkValue='".makeSafe($selected_id)."'");
	$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Compostage' and pkValue='".makeSafe($selected_id)."'");
	if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){ // allow update?
		// update allowed, so continue ...
	}else{
		return false;
	}

	$data['date'] = intval($_REQUEST['dateYear']) . '-' . intval($_REQUEST['dateMonth']) . '-' . intval($_REQUEST['dateDay']);
	$data['date'] = parseMySQLDate($data['date'], '1');
	$data['lieu_compostage'] = makeSafe($_REQUEST['lieu_compostage']);
		if($data['lieu_compostage'] == empty_lookup_value){ $data['lieu_compostage'] = ''; }
	if($data['lieu_compostage']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Lieu compostage': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['matiere'] = makeSafe($_REQUEST['matiere']);
		if($data['matiere'] == empty_lookup_value){ $data['matiere'] = ''; }
	if($data['matiere']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Mati&#232;re': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['poids'] = makeSafe($_REQUEST['poids']);
		if($data['poids'] == empty_lookup_value){ $data['poids'] = ''; }
	if($data['poids']==''){
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Poids': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">'.$Translation['< back'].'</a></div>';
		exit;
	}
	$data['selectedID']=makeSafe($selected_id);

	// hook: Compostage_before_update
	if(function_exists('Compostage_before_update')){
		$args=array();
		if(!Compostage_before_update($data, getMemberInfo(), $args)){ return false; }
	}

	$o=array('silentErrors' => true);
	sql('update `Compostage` set       `date`=' . (($data['date'] !== '' && $data['date'] !== NULL) ? "'{$data['date']}'" : 'NULL') . ', `lieu_compostage`=' . (($data['lieu_compostage'] !== '' && $data['lieu_compostage'] !== NULL) ? "'{$data['lieu_compostage']}'" : 'NULL') . ', `matiere`=' . (($data['matiere'] !== '' && $data['matiere'] !== NULL) ? "'{$data['matiere']}'" : 'NULL') . ', `poids`=' . (($data['poids'] !== '' && $data['poids'] !== NULL) ? "'{$data['poids']}'" : 'NULL') . " where `id`='".makeSafe($selected_id)."'", $o);
	if($o['error']!=''){
		echo $o['error'];
		echo '<a href="Compostage_view.php?SelectedID='.urlencode($selected_id)."\">{$Translation['< back']}</a>";
		exit;
	}


	// hook: Compostage_after_update
	if(function_exists('Compostage_after_update')){
		$res = sql("SELECT * FROM `Compostage` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)){
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = $data['id'];
		$args = array();
		if(!Compostage_after_update($data, getMemberInfo(), $args)){ return; }
	}

	// mm: update ownership data
	sql("update membership_userrecords set dateUpdated='".time()."' where tableName='Compostage' and pkValue='".makeSafe($selected_id)."'", $eo);

}

function Compostage_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = ''){
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm=getTablePermissions('Compostage');
	if(!$arrPerm[1] && $selected_id==''){ return ''; }
	$AllowInsert = ($arrPerm[1] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != ''){
		$dvprint = true;
	}

	$filterer_lieu_compostage = thisOr(undo_magic_quotes($_REQUEST['filterer_lieu_compostage']), '');
	$filterer_matiere = thisOr(undo_magic_quotes($_REQUEST['filterer_matiere']), '');

	// populate filterers, starting from children to grand-parents

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: date
	$combo_date = new DateCombo;
	$combo_date->DateFormat = "dmy";
	$combo_date->MinYear = 1900;
	$combo_date->MaxYear = 2100;
	$combo_date->DefaultDate = parseMySQLDate('1', '1');
	$combo_date->MonthNames = $Translation['month names'];
	$combo_date->NamePrefix = 'date';
	// combobox: lieu_compostage
	$combo_lieu_compostage = new DataCombo;
	// combobox: matiere
	$combo_matiere = new DataCombo;

	if($selected_id){
		// mm: check member permissions
		if(!$arrPerm[2]){
			return "";
		}
		// mm: who is the owner?
		$ownerGroupID=sqlValue("select groupID from membership_userrecords where tableName='Compostage' and pkValue='".makeSafe($selected_id)."'");
		$ownerMemberID=sqlValue("select lcase(memberID) from membership_userrecords where tableName='Compostage' and pkValue='".makeSafe($selected_id)."'");
		if($arrPerm[2]==1 && getLoggedMemberID()!=$ownerMemberID){
			return "";
		}
		if($arrPerm[2]==2 && getLoggedGroupID()!=$ownerGroupID){
			return "";
		}

		// can edit?
		if(($arrPerm[3]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[3]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[3]==3){
			$AllowUpdate=1;
		}else{
			$AllowUpdate=0;
		}

		$res = sql("select * from `Compostage` where `id`='".makeSafe($selected_id)."'", $eo);
		if(!($row = db_fetch_array($res))){
			return error_message($Translation['No records found'], 'Compostage_view.php', false);
		}
		$urow = $row; /* unsanitized data */
		$hc = new CI_Input();
		$row = $hc->xss_clean($row); /* sanitize data */
		$combo_date->DefaultDate = $row['date'];
		$combo_lieu_compostage->SelectedData = $row['lieu_compostage'];
		$combo_matiere->SelectedData = $row['matiere'];
	}else{
		$combo_lieu_compostage->SelectedData = $filterer_lieu_compostage;
		$combo_matiere->SelectedData = $filterer_matiere;
	}
	$combo_lieu_compostage->HTML = '<span id="lieu_compostage-container' . $rnd1 . '"></span><input type="hidden" name="lieu_compostage" id="lieu_compostage' . $rnd1 . '" value="' . html_attr($combo_lieu_compostage->SelectedData) . '">';
	$combo_lieu_compostage->MatchText = '<span id="lieu_compostage-container-readonly' . $rnd1 . '"></span><input type="hidden" name="lieu_compostage" id="lieu_compostage' . $rnd1 . '" value="' . html_attr($combo_lieu_compostage->SelectedData) . '">';
	$combo_matiere->HTML = '<span id="matiere-container' . $rnd1 . '"></span><input type="hidden" name="matiere" id="matiere' . $rnd1 . '" value="' . html_attr($combo_matiere->SelectedData) . '">';
	$combo_matiere->MatchText = '<span id="matiere-container-readonly' . $rnd1 . '"></span><input type="hidden" name="matiere" id="matiere' . $rnd1 . '" value="' . html_attr($combo_matiere->SelectedData) . '">';

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_lieu_compostage__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['lieu_compostage'] : $filterer_lieu_compostage); ?>"};
		AppGini.current_matiere__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['matiere'] : $filterer_matiere); ?>"};

		jQuery(function() {
			setTimeout(function(){
				if(typeof(lieu_compostage_reload__RAND__) == 'function') lieu_compostage_reload__RAND__();
				if(typeof(matiere_reload__RAND__) == 'function') matiere_reload__RAND__();
			}, 10); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function lieu_compostage_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#lieu_compostage-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_lieu_compostage__RAND__.value, t: 'Compostage', f: 'lieu_compostage' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="lieu_compostage"]').val(resp.results[0].id);
							$j('[id=lieu_compostage-container-readonly__RAND__]').html('<span id="lieu_compostage-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Sites_view_parent]').hide(); }else{ $j('.btn[id=Sites_view_parent]').show(); }


							if(typeof(lieu_compostage_update_autofills__RAND__) == 'function') lieu_compostage_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'Compostage', f: 'lieu_compostage' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_lieu_compostage__RAND__.value = e.added.id;
				AppGini.current_lieu_compostage__RAND__.text = e.added.text;
				$j('[name="lieu_compostage"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Sites_view_parent]').hide(); }else{ $j('.btn[id=Sites_view_parent]').show(); }


				if(typeof(lieu_compostage_update_autofills__RAND__) == 'function') lieu_compostage_update_autofills__RAND__();
			});

			if(!$j("#lieu_compostage-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_lieu_compostage__RAND__.value, t: 'Compostage', f: 'lieu_compostage' },
					success: function(resp){
						$j('[name="lieu_compostage"]').val(resp.results[0].id);
						$j('[id=lieu_compostage-container-readonly__RAND__]').html('<span id="lieu_compostage-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Sites_view_parent]').hide(); }else{ $j('.btn[id=Sites_view_parent]').show(); }

						if(typeof(lieu_compostage_update_autofills__RAND__) == 'function') lieu_compostage_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_lieu_compostage__RAND__.value, t: 'Compostage', f: 'lieu_compostage' },
				success: function(resp){
					$j('[id=lieu_compostage-container__RAND__], [id=lieu_compostage-container-readonly__RAND__]').html('<span id="lieu_compostage-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=Sites_view_parent]').hide(); }else{ $j('.btn[id=Sites_view_parent]').show(); }

					if(typeof(lieu_compostage_update_autofills__RAND__) == 'function') lieu_compostage_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function matiere_reload__RAND__(){
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint){ ?>

			$j("#matiere-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c){
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_matiere__RAND__.value, t: 'Compostage', f: 'matiere' },
						success: function(resp){
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="matiere"]').val(resp.results[0].id);
							$j('[id=matiere-container-readonly__RAND__]').html('<span id="matiere-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=matieres_view_parent]').hide(); }else{ $j('.btn[id=matieres_view_parent]').show(); }


							if(typeof(matiere_update_autofills__RAND__) == 'function') matiere_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term){ /* */ return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page){ /* */ return { s: term, p: page, t: 'Compostage', f: 'matiere' }; },
					results: function(resp, page){ /* */ return resp; }
				},
				escapeMarkup: function(str){ /* */ return str; }
			}).on('change', function(e){
				AppGini.current_matiere__RAND__.value = e.added.id;
				AppGini.current_matiere__RAND__.text = e.added.text;
				$j('[name="matiere"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=matieres_view_parent]').hide(); }else{ $j('.btn[id=matieres_view_parent]').show(); }


				if(typeof(matiere_update_autofills__RAND__) == 'function') matiere_update_autofills__RAND__();
			});

			if(!$j("#matiere-container__RAND__").length){
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_matiere__RAND__.value, t: 'Compostage', f: 'matiere' },
					success: function(resp){
						$j('[name="matiere"]').val(resp.results[0].id);
						$j('[id=matiere-container-readonly__RAND__]').html('<span id="matiere-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=matieres_view_parent]').hide(); }else{ $j('.btn[id=matieres_view_parent]').show(); }

						if(typeof(matiere_update_autofills__RAND__) == 'function') matiere_update_autofills__RAND__();
					}
				});
			}

		<?php }else{ ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_matiere__RAND__.value, t: 'Compostage', f: 'matiere' },
				success: function(resp){
					$j('[id=matiere-container__RAND__], [id=matiere-container-readonly__RAND__]').html('<span id="matiere-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>'){ $j('.btn[id=matieres_view_parent]').hide(); }else{ $j('.btn[id=matieres_view_parent]').show(); }

					if(typeof(matiere_update_autofills__RAND__) == 'function') matiere_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint){
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/Compostage_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	}else{
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/Compostage_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Compostage details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert){
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return Compostage_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return Compostage_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']){
		$backAction = 'AppGini.closeParentModal(); return false;';
	}else{
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id){
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate){
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return Compostage_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3){ // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		}else{
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	}else{
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)){
		$jsReadOnly .= "\tjQuery('#date').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#dateDay, #dateMonth, #dateYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#lieu_compostage').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#lieu_compostage_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#matiere').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#matiere_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#poids').replaceWith('<div class=\"form-control-static\" id=\"poids\">' + (jQuery('#poids').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	}elseif($AllowInsert){
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
			$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(date)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_date->GetHTML(true) . '</div>' : $combo_date->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(date)%%>', $combo_date->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(lieu_compostage)%%>', $combo_lieu_compostage->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(lieu_compostage)%%>', $combo_lieu_compostage->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(lieu_compostage)%%>', urlencode($combo_lieu_compostage->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(matiere)%%>', $combo_matiere->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(matiere)%%>', $combo_matiere->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(matiere)%%>', urlencode($combo_matiere->MatchText), $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array(  'lieu_compostage' => array('Sites', 'Lieu compostage'), 'matiere' => array('matieres', 'Mati&#232;re'));
	foreach($lookup_fields as $luf => $ptfc){
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']){
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] && !$_REQUEST['Embedded']){
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(date)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(lieu_compostage)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(matiere)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(poids)%%>', '', $templateCode);

	// process values
	if($selected_id){
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode = str_replace('<%%VALUE(date)%%>', @date('d/m/Y', @strtotime(html_attr($row['date']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode(@date('d/m/Y', @strtotime(html_attr($urow['date'])))), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(lieu_compostage)%%>', safe_html($urow['lieu_compostage']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(lieu_compostage)%%>', html_attr($row['lieu_compostage']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(lieu_compostage)%%>', urlencode($urow['lieu_compostage']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(matiere)%%>', safe_html($urow['matiere']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(matiere)%%>', html_attr($row['matiere']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(matiere)%%>', urlencode($urow['matiere']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(poids)%%>', safe_html($urow['poids']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(poids)%%>', html_attr($row['poids']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(poids)%%>', urlencode($urow['poids']), $templateCode);
	}else{
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(date)%%>', '1', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(date)%%>', urlencode('1'), $templateCode);
		$templateCode = str_replace('<%%VALUE(lieu_compostage)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(lieu_compostage)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(matiere)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(matiere)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(poids)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(poids)%%>', urlencode(''), $templateCode);
	}

	// process translations
	foreach($Translation as $symbol=>$trans){
		$templateCode = str_replace("<%%TRANSLATION($symbol)%%>", $trans, $templateCode);
	}

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == ''){
		$templateCode .= "\n\n<script>\$j(function(){\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption){
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id){
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('Compostage');
	if($selected_id){
		$jdata = get_joined_record('Compostage', $selected_id);
		if($jdata === false) $jdata = get_defaults('Compostage');
		$rdata = $row;
	}
	$templateCode .= loadView('Compostage-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: Compostage_dv
	if(function_exists('Compostage_dv')){
		$args=array();
		Compostage_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}
?>