<?php
// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/Demande.php");
	include("$currDir/Demande_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('Demande');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "Demande";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`Demande`.`id`" => "id",
		"`Demande`.`type`" => "type",
		"`Demande`.`intervention`" => "intervention",
		"IF(    CHAR_LENGTH(`Sites1`.`nom`), CONCAT_WS('',   `Sites1`.`nom`), '') /* Site de compostage */" => "site_compostage",
		"IF(    CHAR_LENGTH(`Sites2`.`nom`), CONCAT_WS('',   `Sites2`.`nom`), '') /* Site de dechet */" => "site_dechet",
		"`Demande`.`desc`" => "desc",
		"if(`Demande`.`date_lancement`,date_format(`Demande`.`date_lancement`,'%d/%m/%Y'),'')" => "date_lancement",
		"if(`Demande`.`date_butoir`,date_format(`Demande`.`date_butoir`,'%d/%m/%Y'),'')" => "date_butoir",
		"if(`Demande`.`date_inter`,date_format(`Demande`.`date_inter`,'%d/%m/%Y'),'')" => "date_inter",
		"`Demande`.`intervenant`" => "intervenant",
		"`Demande`.`prix_unit`" => "prix_unit",
		"`Demande`.`niveau`" => "niveau",
		"`Demande`.`etat`" => "etat"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`Demande`.`id`',
		2 => 2,
		3 => 3,
		4 => '`Sites1`.`nom`',
		5 => '`Sites2`.`nom`',
		6 => 6,
		7 => '`Demande`.`date_lancement`',
		8 => '`Demande`.`date_butoir`',
		9 => '`Demande`.`date_inter`',
		10 => 10,
		11 => '`Demande`.`prix_unit`',
		12 => 12,
		13 => 13
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`Demande`.`id`" => "id",
		"`Demande`.`type`" => "type",
		"`Demande`.`intervention`" => "intervention",
		"IF(    CHAR_LENGTH(`Sites1`.`nom`), CONCAT_WS('',   `Sites1`.`nom`), '') /* Site de compostage */" => "site_compostage",
		"IF(    CHAR_LENGTH(`Sites2`.`nom`), CONCAT_WS('',   `Sites2`.`nom`), '') /* Site de dechet */" => "site_dechet",
		"`Demande`.`desc`" => "desc",
		"if(`Demande`.`date_lancement`,date_format(`Demande`.`date_lancement`,'%d/%m/%Y'),'')" => "date_lancement",
		"if(`Demande`.`date_butoir`,date_format(`Demande`.`date_butoir`,'%d/%m/%Y'),'')" => "date_butoir",
		"if(`Demande`.`date_inter`,date_format(`Demande`.`date_inter`,'%d/%m/%Y'),'')" => "date_inter",
		"`Demande`.`intervenant`" => "intervenant",
		"`Demande`.`prix_unit`" => "prix_unit",
		"`Demande`.`niveau`" => "niveau",
		"`Demande`.`etat`" => "etat"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`Demande`.`id`" => "ID",
		"`Demande`.`type`" => "Type de demande",
		"`Demande`.`intervention`" => "Type d\'Intervention",
		"IF(    CHAR_LENGTH(`Sites1`.`nom`), CONCAT_WS('',   `Sites1`.`nom`), '') /* Site de compostage */" => "Site de compostage",
		"IF(    CHAR_LENGTH(`Sites2`.`nom`), CONCAT_WS('',   `Sites2`.`nom`), '') /* Site de dechet */" => "Site de dechet",
		"`Demande`.`desc`" => "Description",
		"`Demande`.`date_lancement`" => "Date de lancement",
		"`Demande`.`date_butoir`" => "Date butoir",
		"`Demande`.`date_inter`" => "Date d\'intervention",
		"`Demande`.`intervenant`" => "Intervenant",
		"`Demande`.`prix_unit`" => "Prix unitaire",
		"`Demande`.`niveau`" => "Niveau d\'alerte",
		"`Demande`.`etat`" => "Etat d\'avancement"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`Demande`.`id`" => "id",
		"`Demande`.`type`" => "type",
		"`Demande`.`intervention`" => "intervention",
		"IF(    CHAR_LENGTH(`Sites1`.`nom`), CONCAT_WS('',   `Sites1`.`nom`), '') /* Site de compostage */" => "site_compostage",
		"IF(    CHAR_LENGTH(`Sites2`.`nom`), CONCAT_WS('',   `Sites2`.`nom`), '') /* Site de dechet */" => "site_dechet",
		"`Demande`.`desc`" => "desc",
		"if(`Demande`.`date_lancement`,date_format(`Demande`.`date_lancement`,'%d/%m/%Y'),'')" => "date_lancement",
		"if(`Demande`.`date_butoir`,date_format(`Demande`.`date_butoir`,'%d/%m/%Y'),'')" => "date_butoir",
		"if(`Demande`.`date_inter`,date_format(`Demande`.`date_inter`,'%d/%m/%Y'),'')" => "date_inter",
		"`Demande`.`intervenant`" => "intervenant",
		"`Demande`.`prix_unit`" => "prix_unit",
		"`Demande`.`niveau`" => "niveau",
		"`Demande`.`etat`" => "etat"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'site_compostage' => 'Site de compostage', 'site_dechet' => 'Site de dechet');

	$x->QueryFrom = "`Demande` LEFT JOIN `Sites` as Sites1 ON `Sites1`.`id`=`Demande`.`site_compostage` LEFT JOIN `Sites` as Sites2 ON `Sites2`.`id`=`Demande`.`site_dechet` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "Demande_view.php";
	$x->RedirectAfterInsert = "Demande_view.php?SelectedID=#ID#";
	$x->TableTitle = "Demande d'intervention";
	$x->TableIcon = "resources/table_icons/alarm_bell.png";
	$x->PrimaryKey = "`Demande`.`id`";
	$x->DefaultSortField = '`Demande`.`date_lancement`';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Type de demande", "Type d'Intervention", "Site de compostage", "Site de dechet", "Description", "Date de lancement", "Date butoir", "Date d'intervention", "Intervenant", "Prix unitaire", "Niveau d'alerte", "Etat d'avancement");
	$x->ColFieldName = array('type', 'intervention', 'site_compostage', 'site_dechet', 'desc', 'date_lancement', 'date_butoir', 'date_inter', 'intervenant', 'prix_unit', 'niveau', 'etat');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13);

	// template paths below are based on the app main directory
	$x->Template = 'templates/Demande_templateTV.html';
	$x->SelectedTemplate = 'templates/Demande_templateTVS.html';
	$x->TemplateDV = 'templates/Demande_templateDV.html';
	$x->TemplateDVP = 'templates/Demande_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Demande`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Demande' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Demande`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Demande' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`Demande`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: Demande_init
	$render=TRUE;
	if(function_exists('Demande_init')){
		$args=array();
		$render=Demande_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Demande_header
	$headerCode='';
	if(function_exists('Demande_header')){
		$args=array();
		$headerCode=Demande_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: Demande_footer
	$footerCode='';
	if(function_exists('Demande_footer')){
		$args=array();
		$footerCode=Demande_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>