<?php
// This script and data application were generated by AppGini 5.75
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/Sites.php");
	include("$currDir/Sites_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('Sites');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "Sites";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = array(   
		"`Sites`.`id`" => "id",
		"`Sites`.`type`" => "type",
		"`Sites`.`nom`" => "nom",
		"`Sites`.`adress`" => "adress",
		"`Sites`.`code_postal`" => "code_postal",
		"`Sites`.`ville`" => "ville",
		"`Sites`.`nbr`" => "nbr"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`Sites`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => '`Sites`.`nbr`'
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = array(   
		"`Sites`.`id`" => "id",
		"`Sites`.`type`" => "type",
		"`Sites`.`nom`" => "nom",
		"`Sites`.`adress`" => "adress",
		"`Sites`.`code_postal`" => "code_postal",
		"`Sites`.`ville`" => "ville",
		"`Sites`.`nbr`" => "nbr"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters = array(   
		"`Sites`.`id`" => "ID",
		"`Sites`.`type`" => "Type de site de d&#233;chet",
		"`Sites`.`nom`" => "Nom du site",
		"`Sites`.`adress`" => "Adresse",
		"`Sites`.`code_postal`" => "Code postal",
		"`Sites`.`ville`" => "Ville",
		"`Sites`.`nbr`" => "Nombre de semaines d\'ouverture"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS = array(   
		"`Sites`.`id`" => "id",
		"`Sites`.`type`" => "type",
		"`Sites`.`nom`" => "nom",
		"`Sites`.`adress`" => "adress",
		"`Sites`.`code_postal`" => "code_postal",
		"`Sites`.`ville`" => "ville",
		"`Sites`.`nbr`" => "nbr"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom = "`Sites` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 1;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "Sites_view.php";
	$x->RedirectAfterInsert = "Sites_view.php?SelectedID=#ID#";
	$x->TableTitle = "Sites de compostage";
	$x->TableIcon = "resources/table_icons/google_map.png";
	$x->PrimaryKey = "`Sites`.`id`";

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Type de site de d&#233;chet", "Nom du site", "Adresse", "Code postal", "Ville", "Nombre de semaines d'ouverture");
	$x->ColFieldName = array('type', 'nom', 'adress', 'code_postal', 'ville', 'nbr');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7);

	// template paths below are based on the app main directory
	$x->Template = 'templates/Sites_templateTV.html';
	$x->SelectedTemplate = 'templates/Sites_templateTVS.html';
	$x->TemplateDV = 'templates/Sites_templateDV.html';
	$x->TemplateDVP = 'templates/Sites_templateDVP.html';

	$x->ShowTableHeader = 0;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Sites`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Sites' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `Sites`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='Sites' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`Sites`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: Sites_init
	$render=TRUE;
	if(function_exists('Sites_init')){
		$args=array();
		$render=Sites_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: Sites_header
	$headerCode='';
	if(function_exists('Sites_header')){
		$args=array();
		$headerCode=Sites_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: Sites_footer
	$footerCode='';
	if(function_exists('Sites_footer')){
		$args=array();
		$footerCode=Sites_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>