<?php

	// IMPORTANT:
	// ==========
	// When translating, only translate the strings that are
	// TO THE RIGHT OF the arrow sign (=>).
	//
	// Do NOT translate the strings between square brackets ([]) or (<>)
	// =====================================================
	$ReportTranslation = array(
		'back' => "Retour",
		'print report' => "Imprimer Rapport",
		'export report to csv file' => "Export rapport en fichier CSV",
		'records' => "<n> enregistrements",
		'period from to' => "Periode du <FROM> au <TO>",
		'change' => "Change",
		'report configuration' => "Configuration du Rapport",
		'report period' => "Periode du Rapport",
		'month to date' => "Mensuel",
		'month to date description' => 'Inclure les données mensuelles à ce jour. Comparer avec la même période le mois dernier et la même période l\'an dernier.',
		'current month' => "Mois en cours",
		'current month description' => 'Inclure les données de tout le mois en cours. Comparer avec le mois précédent, et le même mois l\'année dernière.',
		'last month' => "Mois dernier",
		'last month description' => 'Inclure les données du mois dernier. Comparer avec le mois précédent et le même mois l\'an dernier.',
		'quarter to date' => "Trimestriel",
		'quarter to date description' => 'Inclure les données du trimestre à ce jour. Comparaison avec la période correspondante du trimestre précédent et la période correspondante de l\'exercice précédent.',
		'current quarter' => "Trimestre en cours",
		'current quarter description' => 'Inclure les données du trimestre courant. Comparer avec le dernier et le même trimestre de l\'année dernière.',
		'last quarter' => "Dernier trimestre",
		'last quarter description' => 'Inclure les données du dernier trimestre. Comparaison avec le trimestre précédent et le trimestre correspondant de l\'exercice précédent.',
		'year to date' => "Annuel",
		'year to date description' => 'Inclure les données depuis le début de l\'année. Comparer avec la même période l\'an dernier et la même période de l\'année précédente.',
		'current year' => "Année en cours",
		'current year description' => 'Inclure les données de l\'année en cours. Comparer avec l\'année dernière et l\'année précédente.',
		'last year' => "Année dernière",
		'last year description' => 'Inclure les données de l\'année dernière. Comparer avec les deux années précédentes.',
		'comparison period 1' => "Période de Comparaison 1",
		'comparison period 2' => "Période de Comparaison 2",
		'from' => "De",
		'to' => "à",
		'order by' => "Trier par ",
		'descending' => "Descendant",
		'ascending' => "Ascendant",
		'appearance' => "Apparance (appliquée immédiatement)",
		'show row numbers' => "Afficher les numéros de ligne",
		'alignment of label column' => "Alignement de la colonne <LABEL> ",
		'alignment of other columns' => "Alignement des autres colonnes",
		'apply' => "Appliquer",
		'close' => "Fermer",
		'charts-color-theme' => 'Charts color theme',
		'rainbow' => 'Rainbow',
		'reds' => 'Red shades',
		'oranges' => 'Orange shades',
		'yellows' => 'Yellow shades',
		'greens' => 'Green shades',
		'blues' => 'Blue shades',
		'violets' => 'Violet shades',
		'grays' => 'Gray shades',
		'barchart-orientation' => 'Orientation de l\'histogramme',
		'barchart-aspect-ratio' => 'Rapport hauteur/largeur de l\'histogramme (hauteur :largeur)',
		'barchart-bar-width' => 'Largeur des barres dans l\'histogramme (pixels)',
		'barchart-bar-spacing' => 'Espacement des barres dans l\'histogramme (pixels)',
		'barchart-bar-width-default-hint' => 'Une valeur de 0 (par defaut) fixe la largeur de la barre automatiquement.',
		'barchart-width' => 'Largeur de l\'histogramme',
		'piechart-width' => 'Largeur des camemberts',
		'piechart-labels' => 'Labels des camemberts',
		'labels' => 'Labels',
		'labels-values' => 'Labels et valeurs',
		'labels-percentages' => 'Labels et pourcentages',
		'labels-values-percentages' => 'Labels, valeurs et pourcentages',
		'automatic' => 'Automatique',
		'loading report header' => 'Chargement de l\'entête du rapport ...',
		'loading report footer' => 'Chargement du pied du rapport ...',
	);